[package]
name = "dbase_expr"
version = "0.2.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
lalrpop-util = { version = "0.20.2", features = ["lexer"] }
regex = "1.11.1"

[build-dependencies]
lalrpop = "0.20.2"
